services:
  # Original template render (for testing)
  remotion-render:
    build: .
    container_name: remotion-render
    volumes:
      - ./out:/usr/src/app/out
    environment:
      - NODE_ENV=production
    command: ["node", "render.mjs"]

  # PR Video Generation (NEW)
  pr-video-render:
    build: .
    container_name: pr-video-render
    volumes:
      - ./out:/usr/src/app/out
    environment:
      - NODE_ENV=production
      # GitHub Configuration (set these via environment or .env file)
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_REPOSITORY=${GITHUB_REPOSITORY}
      - PR_NUMBER=${PR_NUMBER}
      - VIDEO_TYPE=${VIDEO_TYPE:-summary}
      - VIDEO_TITLE=${VIDEO_TITLE}
      - OUTPUT_NAME=${OUTPUT_NAME}
    command: ["npx", "tsx", "render-pr-video.ts"]
  
  remotion-dev:
    build: .
    container_name: remotion-dev
    volumes:
      - ./src:/usr/src/app/src
      - ./out:/usr/src/app/out
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"] 