name: Bug Report
description: Report a bug in the PR video generation system
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report Template
        Use this template to report bugs in the PR video generation system.

  - type: input
    id: bug-title
    attributes:
      label: Bug Title
      description: A clear, descriptive title for this bug
      placeholder: "Example: Video rendering fails for large PRs"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (System broken/unusable)
        - High (Major functionality affected)
        - Medium (Minor functionality affected)
        - Low (Cosmetic/minor issues)
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected by this bug?
      options:
        - GitHub API Integration
        - Video Generation
        - Data Pipeline
        - User Interface
        - Infrastructure
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: "Describe what is happening..."
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: "What should have happened..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened
      placeholder: "What actually happened..."
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Information about your environment
      placeholder: |
        - OS: [e.g. macOS, Linux, Windows]
        - Browser: [e.g. Chrome, Firefox, Safari]
        - Version: [e.g. 1.0.0]
        - Node.js version: [e.g. 18.x]
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs/Error Messages
      description: Any relevant logs or error messages
      placeholder: "Paste logs or error messages here..."
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: "Any additional information..."
    validations:
      required: false